services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    volumes:
      - open-webui:/app/backend/data
    environment:
      - "WEBUI_SECRET_KEY=083cef3c66dfea94e4278a7f39d80c6d5d99ccbe77d96192b5aca95021f6a326"
    restart: unless-stopped

volumes:
  open-webui: {}