services:
  open-webui:
    build: .
    volumes:
      - open-webui:/app/backend/data
    environment:
      - "WEBUI_SECRET_KEY=083cef3c66dfea94e4278a7f39d80c6d5d96192b5aca95021f6a326"
    restart: unless-stopped

volumes:
  open-webui: {}